import math
GRID_DIM_X = 300
GRID_DIM_Y = 200
CELL_SIZE = 4
GRID_WIDTH = GRID_DIM_X * CELL_SIZE
GRID_HEIGHT = GRID_DIM_Y * CELL_SIZE
BATTERY_WIDTH = 30
TOP_BAR_HEIGHT = 40
SCREEN_WIDTH = BATTERY_WIDTH + GRID_WIDTH
SCREEN_HEIGHT = TOP_BAR_HEIGHT + GRID_HEIGHT
ROBOT_RADIUS = 12
HOME_SIZE = math.floor((ROBOT_RADIUS * 2) * 2) + 1
TARGET_FPS = 60
FRAMETIME = math.floor(1000 / TARGET_FPS)
DUST_FREQUENCY = 100
DIRT_SPOT_FREQUENCY = 0.001
