#
# Behavior Tree framework for A1 Behavior trees assignment.
# CS 131 - Artificial Intelligence
#
# Version 3.0.0 - copyright (c) 2023-2024 Santini Fabrizio. All rights reserved.
#

# Definition of the environment variable keys
BATTERY_LEVEL = 'BATTERY_LEVEL'
CHARGING = 'CHARGING'
VACUUMING = 'VACUUMING'


DUSTY_SPOT_SENSOR = 'DUSTY_SPOT_SENSOR'

MY_RADIUS = 'MY_RADIUS'
ROBOT_POSITION = 'ROBOT_POSITION'
HOME_POSITION = 'HOME_POSITION'
HOME_PATH = 'HOME_PATH'


# Spot Cleaning Variables
SPOT_CLEANING = 'SPOT_CLEANING'
SPOT_CLEANING_POSITION = 'SPOT_CLEANING_POSITION'
SPOT_CLEANING_PATH = 'SPOT_CLEANING_PATH'
SPOT_RADIUS = 'SPOT_RADIUS'
SPOT_CURRENT_RADIUS = 'SPOT_CURRENT_RADIUS'
SPOT_CURRENT_ANGLE = 'SPOT_CURRENT_ANGLE'

# General Cleaning Variables
GENERAL_CLEANING = 'GENERAL_CLEANING'
ROOM_DIMENSIONS = 'ROOM_DIMENSIONS'
NEED_TO_CLEAN = 'NEED_TO_CLEAN'